#!/bin/bash
# HZ-OneClick Bootstrapper v3.1 (Force-Reset Edition)
# Auto-generated by Horizon-Hybrid CI

# 1. Force Root
if [ "$(id -u)" -ne 0 ]; then
    echo "Error: Please run as root (sudo -i)."
    exit 1
fi

INSTALL_DIR="/opt/hz-oneclick"
REPO_URL="https://github.com/Hello-Pork-Belly/hz-oneclick.git"

# 2. Ensure Git
if ! command -v git &> /dev/null; then
    echo "Installing Git..."
    if [ -f /etc/debian_version ]; then
        apt-get update -qq && apt-get install -y -qq git
    elif [ -f /etc/redhat-release ]; then
        yum install -y -q git
    fi
fi

# 3. Clone or Force Update
if [ -d "$INSTALL_DIR/.git" ]; then
    echo "Updating HZ-OneClick (Force Reset)..."
    cd "$INSTALL_DIR" || exit 1
    # Fetch latest and hard reset to match remote, discarding local conflicts
    git fetch --all
    git reset --hard origin/main
else
    echo "Installing HZ-OneClick..."
    git clone "$REPO_URL" "$INSTALL_DIR"
    cd "$INSTALL_DIR" || exit 1
fi

# 4. Launch Command Center
if [ -f "lib/entry.sh" ]; then
    chmod +x lib/entry.sh
    exec bash lib/entry.sh
else
    echo "Critical Error: lib/entry.sh not found in downloaded repo!"
    exit 1
fi
